# docker-compose.yml
version: '2'
services:
  ovuze:
    build: .
    restart: always
    ports:
     - "8989:80"
    links:
     - mongo
    environment:
     - MONGO_URL=mongodb://mongo:27017/ovuze
     - ROOT_URL=http://localhost/

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
